######################################################################
#
# File name : tb_max_pool_8ch_simulate.do
# Created on: Fri Jul 28 22:57:08 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L fifo_generator_v13_2_5 -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_max_pool_8ch xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_max_pool_8ch_wave.do}

view wave
view structure
view signals

do {tb_max_pool_8ch.udo}

run 1000ns
