######################################################################
#
# File name : tb_max_pool_8ch_wave.do
# Created on: Fri Jul 28 22:57:08 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
