######################################################################
#
# File name : tb_max_pool_8ch_compile.do
# Created on: Fri Oct 31 01:11:23 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xilinx_vip
vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/fifo_generator_v13_2_5
vlib modelsim_lib/msim/xil_defaultlib

vmap xilinx_vip modelsim_lib/msim/xilinx_vip
vmap xpm modelsim_lib/msim/xpm
vmap fifo_generator_v13_2_5 modelsim_lib/msim/fifo_generator_v13_2_5
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -sv -L axi_vip_v1_1_6 -L processing_system7_vip_v1_0_8 -L xilinx_vip -work xilinx_vip  "+incdir+F:/xilinx/Vivado/2019.2/data/xilinx_vip/include" \
"F:/xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"F:/xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"F:/xilinx/Vivado/2019.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"F:/xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"F:/xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"F:/xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"F:/xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"F:/xilinx/Vivado/2019.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"F:/xilinx/Vivado/2019.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -64 -incr -sv -L axi_vip_v1_1_6 -L processing_system7_vip_v1_0_8 -L xilinx_vip -work xpm  "+incdir+../../../../../src" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/2d50/hdl" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/798b/hdl" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/4fba" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+F:/xilinx/Vivado/2019.2/data/xilinx_vip/include" \
"F:/xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"F:/xilinx/Vivado/2019.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"F:/xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -64 -93 -work xpm  \
"F:/xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -64 -incr -work fifo_generator_v13_2_5  "+incdir+../../../../../src" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/2d50/hdl" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/798b/hdl" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/4fba" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+F:/xilinx/Vivado/2019.2/data/xilinx_vip/include" \
"../../../../project_1.ip_user_files/ipstatic/simulation/fifo_generator_vlog_beh.v" \

vcom -64 -93 -work fifo_generator_v13_2_5  \
"../../../../project_1.ip_user_files/ipstatic/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -64 -incr -work fifo_generator_v13_2_5  "+incdir+../../../../../src" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/2d50/hdl" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/798b/hdl" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/4fba" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+F:/xilinx/Vivado/2019.2/data/xilinx_vip/include" \
"../../../../project_1.ip_user_files/ipstatic/hdl/fifo_generator_v13_2_rfs.v" \

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../src" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/2d50/hdl" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/798b/hdl" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/4fba" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+F:/xilinx/Vivado/2019.2/data/xilinx_vip/include" \
"../../../../project_1.srcs/sources_1/ip/pool_fifo_ip/sim/pool_fifo_ip.v" \
"../../../../../src/max_pool.v" \
"../../../../../src/max_pool_8ch.v" \
"../../../../../sim/tb_max_pool_8ch.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

